[global]
  frame_color = "#A091A133"
  highlight = "#B4C2EA"
  separator_color= "#F7F3F0"

[urgency_low]
  background = "#00000A88"
  foreground = "#F7F3F0"
  frame_color = "#EBE6E133"

[urgency_normal]
  background = "#00000A88"
  foreground = "#F7F3F0"
  frame_color = "#EBE6E133"

[urgency_critical]
  background = "#00000A88"
  foreground = "#F7F3F0"
  frame_color = "#FFA0A033"

