cursor #86BBD9

background #151518
foreground #E7F0F8

color0 #3D3E43
color1 #B76C4C
color2 #2686BA
color3 #8A895C
color4 #C1A4AC
color5 #FFC277
color6 #BAD5EB
color7 #D4E2ED
color8 #949EA6
color9 #B76C4C
color10 #2686BA
color11 #8A895C
color12 #C1A4AC
color13 #FFC277
color14 #BAD5EB
color15 #D4E2ED

mark1_foreground #95C4EB
mark2_foreground #AACFED
mark3_foreground #95C4EB
