cursor #A1D6FD
foreground #DBE3F1
background #20252F

color0 #141923
color1 #F1B8B6
color2 #AED5AE
color3 #CECB99
color4 #A1CFF0
color5 #DFBAE1
color6 #94D6DA
color7 #E0E2E9
color8 #89919D
color9 #FEBBBA
color10 #B0DDB0
color11 #D6D297
color12 #A1D6FD
color13 #E9BEEB
color14 #90DFE3
color15 #EDEFF6
