term xterm-256color

background_opacity 0.8
enable_audio_bell no
font_size 14

editor nvim

map ctrl+shift+q noop
map ctrl+shift+w noop

cursor_shape block
cursor_blink_interval 0

window_padding_width 0 4 0 4

include ~/.config/kitty/colors.conf

# BEGIN_KITTY_FONTS
font_family      family='IosevkaTerm Nerd Font' style=Light
bold_font        family='IosevkaTerm Nerd Font' postscript_name=IosevkaTermNF-SemiBold
italic_font      auto
bold_italic_font family='IosevkaTerm Nerd Font' postscript_name=IosevkaTermNF-SemiBoldItalic
# END_KITTY_FONTS
