term xterm-256color

background_opacity 0.8
enable_audio_bell no
font_size 14

editor nvim

map ctrl+shift+q noop
map ctrl+shift+w noop

cursor_shape block
shell_integration no-cursor

cursor_blink_interval 0

include ~/.config/kitty/ocean.conf

# BEGIN_KITTY_FONTS
font_family      family='IosevkaTerm Nerd Font' style=Light
bold_font        family='IosevkaTerm Nerd Font' style='SemiBold'
italic_font      family='IosevkaTerm Nerd Font' style='Light Italic'
bold_italic_font family='IosevkaTerm Nerd Font' style='SemiBold Italic'
# END_KITTY_FONTS
