term xterm-256color

background_opacity 0.8
enable_audio_bell no
font_size 14

editor nvim

map ctrl+shift+q noop
map ctrl+shift+w noop

window_padding_width 0 5 0 5

include ~/.config/kitty/colors.conf


# BEGIN_KITTY_FONTS
font_family      family="IosevkaTerm Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
