#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

filetype=$(file -Lb --mime-type "$file")

case "${filetype}" in
  image/*) chafa -f sixel -s "${w}x${h}" --animate=off -- "$file" ;;
  text/*) bat -- "$file" ;;
  application/zip | application/x-tar | application/x-xz | application/x-rar | application/gzip | application/x-7z-compressed) 7zz l "$file" ;;
  *) : ;;
esac
