[colors-dark]
cursor={{color0[1:]}} {{foreground[1:]}}
background={{(background | saturate(-0.4))[1:]}}
foreground={{foreground[1:]}}

# Normal/regular colors (color palette 0-7)
regular0=222224          # black
regular1=F4A9A1          # red
regular2=9FD0A9          # green
regular3={{color3[1:]}}  # yellow
regular4={{color4[1:]}}  # blue
regular5={{color5[1:]}}  # magenta
regular6={{color6[1:]}}  # cyan
regular7=D3D5DE          # white

# Bright colors (color palette 8-15)
bright0=2C2E33            # bright black
bright1=F9BDB6            # bright red
bright2=ADDBB6            # bright green
bright3={{color11[1:]}}   # bright yellow
bright4={{color12[1:]}}   # bright blue
bright5={{color13[1:]}}   # bright magenta
bright6={{color14[1:]}}   # bright cyan
bright7=E0E2EA            # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
