[colors-dark]
cursor=00000D F7F3F0
background=04040B
foreground=F7F3F0

# Normal/regular colors (color palette 0-7)
regular0=222224          # black
regular1=F4A9A1          # red
regular2=9FD0A9          # green
regular3=BF746A  # yellow
regular4=A091A1  # blue
regular5=B4C2EA  # magenta
regular6=E7DDD4  # cyan
regular7=D3D5DE          # white

# Bright colors (color palette 8-15)
bright0=2C2E33            # bright black
bright1=F9BDB6            # bright red
bright2=ADDBB6            # bright green
bright3=BF746A   # bright yellow
bright4=A091A1   # bright blue
bright5=B4C2EA   # bright magenta
bright6=E7DDD4   # bright cyan
bright7=E0E2EA            # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
