# Global section - values below can be overwritten by command line flags
backend = "full"
color_space = "lab"
palette = "dark"
check_contrast = true

[templates]

fuzzel = {
  template = 'fuzzel.ini',
  target = '~/.config/fuzzel/colors.ini' 
}

hyprland = {
  template = 'hyprland.lua',
  target = '~/.config/hypr/colors.lua' 
}

kitty = {
  template = 'kitty.conf',
  target = '~/.config/kitty/colors.conf' 
}

neovim = {
  template = 'neovim.lua',
  target = '~/.config/nvim/colors/wallust.lua' 
}

waybar = {
  template = 'waybar.css',
  target = '~/.config/waybar/colors.css' 
}

# foot = {
#   template = 'foot.ini',
#   target = '~/.config/foot/colors.ini' 
# }
# dunst = {
#   template = 'dunst',
#   target = '~/.config/dunst/dunstrc.d/99-colors.conf' 
# }
# rofi = {
#   template = 'rofi.rasi',
#   target = '~/.config/rofi/current.rasi' 
# }
# sway = {
#   template = 'sway',
#   target = '~/.config/sway/colors' 
# }
# wofi = {
#   template = 'wofi',
#   target = '~/.config/wofi/colors' 
# }
