# AUTOSTART

# $polkit = /usr/lib/polkit-kde-authentication-agent-1 &
# $dbusenv = dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY &
$bar = waybar

exec-once = $bar
exec-once = mpd
# exec-once = $polkit
# exec-once = $dbusenv
