# VARIABLES
$terminal = foot
$laptopMonitor = eDP-1
$laptopConfig = $laptopMonitor,preferred,auto,1.2
$browser = brave
$fileManager = foot -a yazi -T yazi yazi
$menu = rofi -show drun
$music = foot -a rmpc -T rmpc rmpc
$windowSwitcher = rofi -show window
$wallpaper = swaybg -i "${HOME}/.cache/wallpaper" -m fill &

# LOAD CONFIGS
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/ui.conf

# ESSENTIAL AUTOSTART
exec-once = $terminal
exec-once = $wallpaper

# MONITORS
monitor = $laptopConfig
monitor = HDMI-A-1,preferred,auto,1

# ENVIRONMENT VARIABLES
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24
