#!/bin/bash
#
# A wallpaper selector script for setting the wallpaper using swaybg
# and update the colorscheme using wallust

WALLPAPERS="${WALLPAPERS:-$HOME/Pictures/Wallpapers}"

WALLPAPER_PATH="$HOME/.cache/wallpaper"
DEPENDENCIES=("nsxiv" "swaybg")

# Send notification and exit on error.
send_error_notification() {
  notify-send -u critical "  Error" "$1"
  exit 1
}

check_dependencies() {
  for cmd in "${DEPENDENCIES[@]}"; do
    if ! command -v "$cmd" &>/dev/null; then
      send_error_notification "Required command not found: $cmd"
    fi
  done
}

restart_waybar() {
  pkill waybar && waybar &
  disown
}

update_colorscheme() {
  if ! command -v wallust &>/dev/null; then
    notify-send -u critical " Error" \
      "Wallust not found for updating the colorscheme"
    return 1
  fi
  if wallust run "$WALLPAPER_PATH" -q; then
    refresh_waybar
  else
    notify-send -u critical " Error" \
      "Failed to update colorscheme with wallust"
    return 1
  fi
}

main() {
  # Ensure no other nsxiv instances are running
  if pgrep -x "nsxiv" >/dev/null; then
    exit 1
  fi

  # Verify wallpapers directory exists
  if [[ ! -d "$WALLPAPERS" ]]; then
    send_error_notification "Wallpapers directory does not exist: $WALLPAPERS"
  fi

  check_dependencies

  notify-send "Wallpaper Selector" "Press 'Q' to select"

  # Launch nsxiv to pick wallpaper
  wallpaper="$(nsxiv -b "$WALLPAPERS" -rot)"

  if [[ -f "$wallpaper" ]]; then
    ln -sf "$wallpaper" "$WALLPAPER_PATH"
    pkill swaybg
    swaybg -i "$wallpaper" -m fill &
    disown
    update_colorscheme
  fi
}

main "$@"
