#!/bin/bash
#
# A wallpaper selector script for setting the wallpaper using swaybg
# and update the colorscheme using wallust

WALLPAPERS="${WALLPAPERS:-$HOME/Pictures/Wallpapers}"

readonly WALLPAPER_PATH="$HOME/.cache/wallpaper"
readonly DEPENDENCIES=("nsxiv" "swaybg")

# Send message to STDERR and as notification
err() {
  echo "$*" >&2
  notify-send -u critical "  Error" "$*"
}

# Check for missing dependencies
check_dependencies() {
  declare -a missing_deps

  for cmd in "$@"; do
    if ! command -v "$cmd" &>/dev/null; then
      missing_deps+=("$cmd")
    fi
  done

  if [[ "${#missing_deps[@]}" -gt 0 ]]; then
    err "Missing dependencies: ${missing_deps[*]}"
    exit 1
  fi

}

restart_waybar() {
  pkill waybar && waybar &
  disown
}

update_colorscheme() {

  if ! command -v wallust &>/dev/null; then
    err "Wallust not found for updating the colorscheme"
    return 1
  fi

  if wallust run "$WALLPAPER_PATH" -q; then
    restart_waybar
  else
    err "Failed to update colorscheme with wallust"
    return 1
  fi
}

# Update wallpaper using swaybg
set_wallpaper() {
  local wallpaper="${1:?"Wallpaper path required"}"
  echo "$?"

  if [[ -f "$wallpaper" ]]; then
    ln -sf "$wallpaper" "$WALLPAPER_PATH"
    pkill swaybg
    swaybg -i "$wallpaper" -m fill &
    disown
    update_colorscheme
  fi
}

main() {

  check_dependencies "${DEPENDENCIES[@]}"

  local wallpaper="$1"

  if [[ -f "$wallpaper" ]]; then
    set_wallpaper "$wallpaper"
    return 0
  fi

  # Ensure no other nsxiv instances are running
  if pgrep -x "nsxiv" >/dev/null; then
    exit 1
  fi

  # Ensure wallpapers directory exists
  if [[ ! -d "$WALLPAPERS" ]]; then
    err "Wallpapers directory does not exist: $WALLPAPERS"
  fi

  notify-send "Wallpaper Selector" "Press 'Q' to select"

  # Launch nsxiv to pick wallpaper
  wallpaper="$(nsxiv -b "$WALLPAPERS" -rot)"
  set_wallpaper "$wallpaper"

}

main "$@"
