#!/bin/bash

readonly DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/clipboard"
readonly CLIPBOARD="${DATA_HOME}/clipboard"
readonly TRASH="${DATA_HOME}/trash"

err() {
  echo "$@" >&2
}

check_dependencies() {
  declare -a missing_deps

  if ! command -v "rofi" &>/dev/null; then
    missing_deps+=("rofi")
  fi

  if ! command -v "wl-copy" &>/dev/null; then
    missing_deps+=("wl-clipboard")
  fi

  if [[ "${#missing_deps[@]}" -gt 0 ]]; then
    err "Missing dependencies: ${missing_deps[*]}"
    exit 1
  fi
}

check_rofi_running() {
  if pgrep -x "rofi" >/dev/null; then
    exit 1
  fi
}

show_help() {
  printf "Usage: clipboard <OPTION>

  -a, --add
                  add clipboard content to the storage
  -d, --delete
                  delete entry from the storage
  -c, --copy
                  copy from storage to the system clipboard
  -h, --help
                  display help\n"
}

add_to_storage() {
  text="$(wl-paste)"
  [ -z "$text" ] && exit 1

  # Compress newlines to literal \n for single-line storage
  compact_text="$(echo "$text" | awk 1 ORS='\\n')"

  if ! grep -Fx "$compact_text" "$CLIPBOARD" >/dev/null 2>&1; then
    printf "%s\n" "$compact_text" >>"$CLIPBOARD"
  fi
}

delete_from_storage() {
  local text match line_number

  check_rofi_running

  # exit on empty storage
  [ ! -s "$CLIPBOARD" ] && exit 0

  text="$(rofi -dmenu -theme dmenu -no-custom -p 'Delete' <"$CLIPBOARD")"
  [ -z "$text" ] && exit 1

  match="$(grep -Fx "$text" -n "$CLIPBOARD")"

  if [[ -n "$match" ]]; then
    line_number="${match%%:*}"
    sed -i "${line_number}d" "$CLIPBOARD"
    printf "%s\n" "$text" >>"$TRASH"
  fi
}

copy_to_clipboard() {

  check_rofi_running

  # exit on empty storage
  [ ! -s "$CLIPBOARD" ] && exit 0

  text="$(rofi -dmenu -theme dmenu -no-custom -p 'Copy' <"$CLIPBOARD")"
  [ -z "$text" ] && exit 1

  wl-copy "$(printf '%b' "$text")"
}

main() {
  check_dependencies

  # Create clipboard directory and file if needed
  mkdir -p "$DATA_HOME"
  touch "$CLIPBOARD"

  # Enforce exactly one argument
  if [ "$#" -ne 1 ]; then
    show_help
    exit 1
  fi

  case "$1" in
  -a | --add) add_to_storage ;;
  -d | --delete) delete_from_storage ;;
  -c | --copy) copy_to_clipboard ;;
  -h | --help)
    show_help
    exit 0
    ;;
  *)
    show_help
    exit 1
    ;;
  esac
}

main "$@"
