#!/bin/bash

# Set clipboard path with default
CLIPBOARD="${CLIPBOARD:-$HOME/.local/share/clipboard/clipboard}"

# Save clipboard directory path once
CLIPBOARD_DIR="$(dirname "$CLIPBOARD")"

# Create clipboard directory if needed
mkdir -p "$CLIPBOARD_DIR"

# Define trash file inside the same directory
TRASH="$CLIPBOARD_DIR/trash.txt"

print_help() {
  echo "Usage: clipboard [options]"
  echo "Options:"
  printf "  %-4s %s\n" "-a" "Add content of system clipboard to clipboard file"
  printf "  %-4s %s\n" "-d" "Delete entry from clipboard file"
  printf "  %-4s %s\n" "-p" "Copy clipboard file entry to system clipboard"
  exit 1
}

add_to_clipboard() {
  text="$(wl-paste)"
  [ -z "$text" ] && exit 1
  compact_text=$(echo "$text" | awk '{printf "%s%s", (NR>1 ? "\\n" : ""), $0}')
  if ! grep -Fx "$compact_text" "$CLIPBOARD"; then
    printf "%s\n" "$compact_text" >>"$CLIPBOARD"
  fi
}

delete_from_clipboard() {
  text="$(cat "$CLIPBOARD" | rofi -dmenu -no-custom -p 'Delete')"
  sed "\|$text|d" -i "$CLIPBOARD" && echo "$text" >>"$TRASH"
}

copy_to_clipboard() {
  text="$(cat "$CLIPBOARD" | rofi -dmenu -no-custom -p 'Copy')"
  [ -n "$text" ] && wl-copy "$(echo -e "$text")"
}

if pgrep -f "^wofi"; then
  exit 1
fi

while getopts ":adp" flag; do
  case "$flag" in
  a)
    add_to_clipboard
    ;;
  d)
    delete_from_clipboard
    ;;
  p)
    copy_to_clipboard
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    print_help
    ;;
  esac
done

if [ -z "$1" ]; then
  print_help
fi
