#!/bin/bash

SCREENSHOT_PATH="$HOME/Pictures/Screenshots"

# Ensure directory exists
if [ ! -d "$SCREENSHOT_PATH" ];then
	mkdir -p "$SCREENSHOT_PATH" -v
fi

# Generate timestamped filename
filename="$(date '+%Y-%m-%d-%H-%M-%S.png')"

# Take screenshot
if grim "$SCREENSHOT_PATH/$filename"; then
    notify-send "  Screenshot Captured" "$filename"
else
    notify-send "  Screenshot failed" -u critical
fi
